#!/usr/bin/perl
use strict;
use warnings;

sub copyConfigFile($;$);
sub run(@);

sub main(@){
  system "adb", "kill-server";
  system "adb", "root";

  system "adb", "remount";

  my $sshDir = "/data/ssh";
  run "adb", "shell", "rm", "-rf", "$sshDir";
  run "adb", "shell", "mkdir", "-p", "$sshDir/empty";
  run "adb", "shell", "chmod", "700", "$sshDir";
  run "adb", "shell", "chmod", "700", "/$sshDir/empty";
  run "adb", "shell", "/system/bin/ssh-keygen", "-t", "rsa", "-N", "''", "-f", "$sshDir/id_rsa";
  run "adb", "shell", "chmod", "600", "$sshDir/id_rsa",
  run "adb", "shell", "mv", "$sshDir/id_rsa.pub", "$sshDir/wolke-s5.pub",

  my @files;

  @files = glob "$ENV{HOME}/.ssh/*.pub";
  for my $f(@files){
    $f = `basename "$f"`;
    chomp $f;
    run "adb", "push", "$ENV{HOME}/.ssh/$f", "$sshDir/$f";
  }
  run "adb", "shell", "cat $sshDir/*.pub > $sshDir/authorized_keys";
  run "adb", "pull", "$sshDir/wolke-s5.pub", "$ENV{HOME}/.ssh/wolke-s5.pub";
  run "cat $ENV{HOME}/.ssh/*.pub > $ENV{HOME}/.ssh/authorized_keys";

  copyConfigFile "%etc%ssh%sshd_config";

  copyConfigFile "%etc%init.d%08selinux", "755";
  copyConfigFile "%etc%init.d%99sshd", "755";
  copyConfigFile "%system%su.d%99sshd_supolicy", "755";
}

sub copyConfigFile($;$){
  my ($configFile, $perms) = @_;
  my $localFile = "CONFIG_FILES/$configFile";

  my $remoteFile = $configFile;
  $remoteFile =~ s/%/\//g;

  my $remoteDir = $remoteFile;
  $remoteDir =~ s/\/[^\/]*$//;

  run "adb", "shell", "mkdir", "-p", $remoteDir;
  run "adb", "push", $localFile, $remoteFile;
  if(defined $perms){
    run "adb", "shell", "chmod", $perms, $remoteFile;
  }
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
