#!/usr/bin/perl
use strict;
use warnings;

sub run(@);

sub main(@){
  system "adb", "kill-server";
  system "adb", "root";

  system "adb", "remount";

  my $sshDir = "/data/ssh";
  run "adb", "shell", "rm", "-rf", "$sshDir";
  run "adb", "shell", "mkdir", "-p", "$sshDir/empty";
  run "adb", "shell", "chmod", "700", "$sshDir";
  run "adb", "shell", "chmod", "700", "/$sshDir/empty";
  run "adb", "shell", "/system/bin/ssh-keygen", "-t", "rsa", "-N", "''", "-f", "$sshDir/id_rsa";
  run "adb", "shell", "chmod", "600", "$sshDir/id_rsa",
  run "adb", "shell", "mv", "$sshDir/id_rsa.pub", "$sshDir/wolke-s5.pub",

  my @files;

  @files = glob "$ENV{HOME}/.ssh/*.pub";
  for my $f(@files){
    $f = `basename "$f"`;
    chomp $f;
    run "adb", "push", "$ENV{HOME}/.ssh/$f", "$sshDir/$f";
  }
  run "adb", "shell", "cat $sshDir/*.pub > $sshDir/authorized_keys";
  run "adb", "pull", "$sshDir/wolke-s5.pub", "$ENV{HOME}/.ssh/wolke-s5.pub";
  run "cat $ENV{HOME}/.ssh/*.pub > $ENV{HOME}/.ssh/authorized_keys";

  run "adb", "push", "CONFIG_FILES/%etc%ssh%sshd_config", "/etc/ssh/sshd_config";

  run "adb", "shell", "mkdir", "-p", "/etc/init.d";

  run "adb", "push", "CONFIG_FILES/%etc%init.d%08selinux", "/etc/init.d/08selinux";
  run "adb", "shell", "chmod", "755", "/etc/init.d/08selinux";

  run "adb", "push", "CONFIG_FILES/%etc%init.d%99sshd", "/etc/init.d/99sshd";
  run "adb", "shell", "chmod", "755", "/etc/init.d/99sshd";

  run "adb", "shell", "mkdir", "-p", "/system/su.d";
  run "adb", "push", "CONFIG_FILES/%system%su.d%99sshd_supolicy", "/system/su.d/99sshd_supolicy";
  run "adb", "shell", "chmod", "755", "/system/su.d/99sshd_supolicy";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
