#!/usr/bin/perl
use strict;
use warnings;

sub readWinfoNetworks();
sub setNetworkPriorities(@);

sub main(@){
  my @networks = readWinfoNetworks();
  @networks = setNetworkPriorities @networks;
}

sub readWinfoNetworks(){
  my @networks;
  my @ssids = sort split /\n/, `winfo --list-all`;
  for my $ssidName(@ssids){
    my $info = `winfo "$ssidName"`;
    my $ssid = $1 if $info =~ /^ssid:(.*)$/m;
    my $enc = $1 if $info =~ /^enc:(.*)$/m;
    my $key = $1 if $info =~ /^key:(.*)$/m;
    my $mode = $1 if $info =~ /^mode:(.*)$/m;
    my $auto = $1 if $info =~ /^auto:(.*)$/m;
    if($enc =~ /^(WPA|WEP|NONE)/i and $mode =~ /managed/i){
      push @networks, {
        ssid => $ssid,
        enc  => $enc,
        key  => $key,
        auto => $auto,
      };
    }
  }

  return @networks;
}

sub setNetworkPriorities(@){
  my @networks = @_;

  my $count = @networks;

  @networks = sort {
    my $aAuto = $$a{auto} =~ /^\d+$/ ? $$a{auto} : $count;
    my $bAuto = $$b{auto} =~ /^\d+$/ ? $$b{auto} : $count;

    return $aAuto <=> $bAuto || $$a{ssid} cmp $$b{ssid};
  } @networks;

  #higher number is higher priority
  @networks = reverse @networks;

  my $i=1;
  for my $network(@networks){
    $$network{priority} = $i++;
  }

  return @networks;
}

&main(@ARGV);
